// Destinos de TourPlan — lista FIJA, generada el 2026-07-15.
//
// Este proyecto no tiene acceso a TourPlan (no hay mssql ni credenciales TP acá),
// así que la lista se genera desde TP y se versiona. Los destinos de TP cambian
// muy de vez en cuando; si falta alguno, agregarlo a mano acá.
//
// Fuente: vw_ProductHeaderReportData (ProductLocationCode / ProductLocationName),
// 334 destinos con productos cargados. El `code` es lo que se graba en la
// nota de TP ("Destino: MDZ"); el nombre es solo para que el desplegable se lea.

export type DestinoTP = { code: string; nombre: string }

export const DESTINOS_TP: DestinoTP[] = [
  { code: 'AGS', nombre: 'Agostini Sound' },
  { code: 'ACA', nombre: 'Aguas Calientes' },
  { code: 'AHU', nombre: 'Ahuano' },
  { code: 'BAW', nombre: 'Ainsworth Bay' },
  { code: 'MAN', nombre: 'Amantani' },
  { code: 'AMA', nombre: 'Amazonas' },
  { code: 'ANC', nombre: 'Ancud' },
  { code: 'ANG', nombre: 'Angra dos Reis' },
  { code: 'ATP', nombre: 'Antarctic Peninsula' },
  { code: 'ANF', nombre: 'Antofagasta' },
  { code: 'AFS', nombre: 'Antofagasta de la Sierra' },
  { code: 'ATF', nombre: 'Antofalla' },
  { code: 'AQP', nombre: 'Arequipa' },
  { code: 'ARI', nombre: 'Arica' },
  { code: 'AXM', nombre: 'Armenia' },
  { code: 'ASU', nombre: 'Asunción' },
  { code: 'ATA', nombre: 'Atacama' },
  { code: 'AVT', nombre: 'Avia Terai' },
  { code: 'AYS', nombre: 'Aysen' },
  { code: 'BHI', nombre: 'Bahia Blanca' },
  { code: 'BBU', nombre: 'Bahia Bustamante' },
  { code: 'BAJ', nombre: 'Bajo Caracoles' },
  { code: 'BBA', nombre: 'Balmaceda' },
  { code: 'BRC', nombre: 'Bariloche' },
  { code: 'BRL', nombre: 'Barreal' },
  { code: 'BAR', nombre: 'Barreirinhas' },
  { code: 'BRB', nombre: 'Barreirinhas (no usar)' },
  { code: 'BLN', nombre: 'Belen' },
  { code: 'BEL', nombre: 'Belen' },
  { code: 'BVT', nombre: 'Bella Vista' },
  { code: 'BVS', nombre: 'Bella Vista Sur' },
  { code: 'BHZ', nombre: 'Belo Horizonte' },
  { code: 'BOG', nombre: 'Bogotá' },
  { code: 'BNT', nombre: 'Bonito' },
  { code: 'BSB', nombre: 'Brasilia' },
  { code: 'BUE', nombre: 'Buenos Aires' },
  { code: 'BUZ', nombre: 'Buzios' },
  { code: 'CDH', nombre: 'Cabo de Hornos' },
  { code: 'CEU', nombre: 'Cacheuta' },
  { code: 'CAC', nombre: 'Cachi' },
  { code: 'CAF', nombre: 'Cafayate' },
  { code: 'CA', nombre: 'Cajamarca' },
  { code: 'CJC', nombre: 'Calama' },
  { code: 'CGL', nombre: 'Caleta Gonzalo' },
  { code: 'CLT', nombre: 'Caleta Tortel' },
  { code: 'CLO', nombre: 'Cali' },
  { code: 'CGD', nombre: 'Campo Grande' },
  { code: 'CAJ', nombre: 'Canaima' },
  { code: 'CCO', nombre: 'Cañon del Colca' },
  { code: 'CAH', nombre: 'Cape Horn' },
  { code: 'CCS', nombre: 'Caracas' },
  { code: 'CCL', nombre: 'Carilo' },
  { code: 'IQQ', nombre: 'Cariquima' },
  { code: 'CPG', nombre: 'Carlos Pellegrini' },
  { code: 'CAR', nombre: 'Carmelo' },
  { code: 'CTG', nombre: 'Cartagena' },
  { code: 'CAU', nombre: 'Caruaru' },
  { code: 'CAS', nombre: 'Castro' },
  { code: 'CTC', nombre: 'Catamarca' },
  { code: 'CUY', nombre: 'Cayena' },
  { code: 'CSO', nombre: 'Cerro Sombrero' },
  { code: 'CHH', nombre: 'Chachapoyas' },
  { code: 'CDC', nombre: 'Chacras de Coria' },
  { code: 'CIT', nombre: 'Chaiten' },
  { code: 'CIX', nombre: 'Chiclayo' },
  { code: 'CCH', nombre: 'Chile Chico' },
  { code: 'CHI', nombre: 'Chilecito' },
  { code: 'COE', nombre: 'Chiloe' },
  { code: 'CML', nombre: 'Chos Malal' },
  { code: 'CHU', nombre: 'Chubut' },
  { code: 'CDE', nombre: 'Ciudad del Este' },
  { code: 'OCC', nombre: 'Coca' },
  { code: 'CBB', nombre: 'Cochabamba' },
  { code: 'CHM', nombre: 'Cochamo' },
  { code: 'TRM', nombre: 'Cochrane' },
  { code: 'IND', nombre: 'Col. Independencia' },
  { code: 'CHG', nombre: 'Colchagua' },
  { code: 'COL', nombre: 'Colonia' },
  { code: 'CIN', nombre: 'Colonia Independencia' },
  { code: 'CMR', nombre: 'Comodoro Rivadavia' },
  { code: 'CNR', nombre: 'Coñaripe' },
  { code: 'CCP', nombre: 'Concepcion' },
  { code: 'CNP', nombre: 'Concepcion' },
  { code: 'CEP', nombre: 'Concepción' },
  { code: 'CIO', nombre: 'Concepción' },
  { code: 'COP', nombre: 'Copacabana' },
  { code: 'COQ', nombre: 'Coquimbo' },
  { code: 'COR', nombre: 'Cordoba' },
  { code: 'CNQ', nombre: 'Corrientes' },
  { code: 'CRT', nombre: 'Corrientes' },
  { code: 'CTX', nombre: 'Cotopaxi' },
  { code: 'COY', nombre: 'Coyhaique' },
  { code: 'CUE', nombre: 'Cuenca' },
  { code: 'CUI', nombre: 'Cuiaba' },
  { code: 'CRN', nombre: 'Curacautin' },
  { code: 'CWB', nombre: 'Curitiba' },
  { code: 'CUZ', nombre: 'Cusco' },
  { code: 'DSG', nombre: 'Desaguadero' },
  { code: 'EHL', nombre: 'El Bolson' },
  { code: 'FTE', nombre: 'El Calafate' },
  { code: 'CHL', nombre: 'El Chalten' },
  { code: 'HOY', nombre: 'El Hoyo' },
  { code: 'PNI', nombre: 'El Impenetrable' },
  { code: 'EMO', nombre: 'El Molle' },
  { code: 'PEÑ', nombre: 'El Peñon' },
  { code: 'ENC', nombre: 'Encarnacion' },
  { code: 'EPU', nombre: 'Epuyén' },
  { code: 'EQS', nombre: 'Esquel' },
  { code: 'ESQ', nombre: 'Esquina' },
  { code: 'FAR', nombre: 'Farellones' },
  { code: 'FDN', nombre: 'Fernando de Noronha' },
  { code: 'FMB', nombre: 'Fiambala' },
  { code: 'FIL', nombre: 'Filadelfia' },
  { code: 'FLN', nombre: 'Florianopolis' },
  { code: 'FLA', nombre: 'Florida' },
  { code: 'FMA', nombre: 'Formosa' },
  { code: 'FOR', nombre: 'Fortaleza' },
  { code: 'IGU', nombre: 'Foz de Iguazu' },
  { code: 'FUT', nombre: 'Futaleufu' },
  { code: 'GAI', nombre: 'Gaiman' },
  { code: 'GDF', nombre: 'Ganchos de Fora' },
  { code: 'GEO', nombre: 'Georgetown' },
  { code: 'GGS', nombre: 'Gobernador Gregores' },
  { code: 'GRA', nombre: 'Gramado' },
  { code: 'GHU', nombre: 'Gualeguaychu' },
  { code: 'GYE', nombre: 'Guayaquil' },
  { code: 'HOR', nombre: 'Hornaditas' },
  { code: 'HNP', nombre: 'Hornopiren' },
  { code: 'HTJ', nombre: 'Huatajata' },
  { code: 'HIO', nombre: 'Huilo Huilo' },
  { code: 'HUM', nombre: 'Humahuaca' },
  { code: 'IBE', nombre: 'Ibera' },
  { code: 'ICA', nombre: 'Ica' },
  { code: 'QDO', nombre: 'Icoaraci' },
  { code: 'ILG', nombre: 'Ilha Grande' },
  { code: 'IOS', nombre: 'Ilheus' },
  { code: 'IQU', nombre: 'Iquique' },
  { code: 'IQT', nombre: 'Iquitos' },
  { code: 'IRU', nombre: 'Iruya' },
  { code: 'ISI', nombre: 'Isinlivi' },
  { code: 'IBR', nombre: 'Isla Baru' },
  { code: 'IPC', nombre: 'Isla de Pascua' },
  { code: 'IDS', nombre: 'Isla del Sol' },
  { code: 'ISG', nombre: 'Isla Grande no usar' },
  { code: 'ISA', nombre: 'Isla Isabela' },
  { code: 'INV', nombre: 'Isla Navarino' },
  { code: 'IRC', nombre: 'Isla Robinson Crusoe' },
  { code: 'SCI', nombre: 'Isla San Cristobal' },
  { code: 'ISC', nombre: 'Isla Santa Cruz' },
  { code: 'GPS', nombre: 'Islas Galápagos' },
  { code: 'IWO', nombre: 'Iwokrama' },
  { code: 'JJD', nombre: 'Jericoacoara' },
  { code: 'JIG', nombre: 'Jose Ignacio' },
  { code: 'JUJ', nombre: 'Jujuy' },
  { code: 'LJT', nombre: 'La Junta' },
  { code: 'LPM', nombre: 'La Paloma' },
  { code: 'LPB', nombre: 'La Paz' },
  { code: 'LPT', nombre: 'La Plata' },
  { code: 'QUI', nombre: 'La Quiaca' },
  { code: 'IRJ', nombre: 'La Rioja' },
  { code: 'LSC', nombre: 'La Serena' },
  { code: 'LST', nombre: 'La Serena (NO USAR)' },
  { code: 'LPO', nombre: 'Lago Posadas' },
  { code: 'LYC', nombre: 'Lago Yelcho' },
  { code: 'GRU', nombre: 'Las Grutas' },
  { code: 'LGS', nombre: 'Las Leñas' },
  { code: 'LTR', nombre: 'Las Trancas' },
  { code: 'LIM', nombre: 'Lima' },
  { code: 'LOA', nombre: 'Los Andes' },
  { code: 'ANT', nombre: 'Los Antiguos' },
  { code: 'LAN', nombre: 'Los Antiguos' },
  { code: 'MCS', nombre: 'Maceio' },
  { code: 'MAC', nombre: 'Machu Pichu' },
  { code: 'MGL', nombre: 'Magallanes' },
  { code: 'MAI', nombre: 'Maipu' },
  { code: 'MLL', nombre: 'Malalcahuello' },
  { code: 'MLG', nombre: 'Malargüe' },
  { code: 'MAO', nombre: 'Manaos' },
  { code: 'MZL', nombre: 'Manizales' },
  { code: 'MDQ', nombre: 'Mar del Plata' },
  { code: 'MAR', nombre: 'Marau' },
  { code: 'MBA', nombre: 'Mbaracayú' },
  { code: 'MDE', nombre: 'Medellin' },
  { code: 'MDZ', nombre: 'Mendoza' },
  { code: 'MER', nombre: 'Mercedes' },
  { code: 'MHU', nombre: 'Millahue' },
  { code: 'MOC', nombre: 'Mocona' },
  { code: 'MOL', nombre: 'Molinos' },
  { code: 'MVD', nombre: 'Montevideo' },
  { code: 'NAU', nombre: 'Nauta' },
  { code: 'NEC', nombre: 'Necochea' },
  { code: 'NEL', nombre: 'Neltume' },
  { code: 'NQN', nombre: 'Neuquen' },
  { code: 'NCH', nombre: 'Nevados de Chillán' },
  { code: 'OBE', nombre: 'Obera' },
  { code: 'ONA', nombre: 'Onaisin' },
  { code: 'OSO', nombre: 'Osorno' },
  { code: 'OTV', nombre: 'Otavalo' },
  { code: 'OPT', nombre: 'Ouro Preto' },
  { code: 'PAG', nombre: 'Panguipulli' },
  { code: 'PAN', nombre: 'Pantanal' },
  { code: 'PCS', nombre: 'Paracas' },
  { code: 'PBM', nombre: 'Paramaribo' },
  { code: 'PAR', nombre: 'Paraná' },
  { code: 'PRA', nombre: 'Paraty' },
  { code: 'PPA', nombre: 'Parque Nac Patagonia' },
  { code: 'PNA', nombre: 'Parque Nacional Los Alerces' },
  { code: 'PDT', nombre: 'Paso de los Toros' },
  { code: 'PVS', nombre: 'Península Valdés' },
  { code: 'PEI', nombre: 'Pereira' },
  { code: 'PMQ', nombre: 'Perito Moreno' },
  { code: 'PET', nombre: 'Petropolis' },
  { code: 'PEU', nombre: 'Peulla' },
  { code: 'PIA', nombre: 'Pia Glacier' },
  { code: 'PIC', nombre: 'Pica' },
  { code: 'PIG', nombre: 'Pigüé' },
  { code: 'PIR', nombre: 'Piriapolis' },
  { code: 'PIS', nombre: 'Pisco' },
  { code: 'PNP', nombre: 'PN Patagonia' },
  { code: 'PDG', nombre: 'Porto de Galinhas' },
  { code: 'BPS', nombre: 'Porto Seguro' },
  { code: 'PSS', nombre: 'Posadas' },
  { code: 'POT', nombre: 'Potosí' },
  { code: 'PTR', nombre: 'Potrerillos' },
  { code: 'PDF', nombre: 'Praia Do Forte' },
  { code: 'PUC', nombre: 'Pucón' },
  { code: 'POA', nombre: 'Puerto Alegre' },
  { code: 'PBT', nombre: 'Puerto Bertrand' },
  { code: 'PTC', nombre: 'Puerto Chacabuco' },
  { code: 'PGU', nombre: 'Puerto Guadal' },
  { code: 'IGR', nombre: 'Puerto Iguazu' },
  { code: 'PTL', nombre: 'Puerto López' },
  { code: 'PMY', nombre: 'Puerto Madryn' },
  { code: 'PEM', nombre: 'Puerto Maldonado' },
  { code: 'PMC', nombre: 'Puerto Montt' },
  { code: 'PNT', nombre: 'Puerto Natales' },
  { code: 'PPM', nombre: 'Puerto Piramides' },
  { code: 'PSJ', nombre: 'Puerto San Julian' },
  { code: 'PTT', nombre: 'Puerto Tranquilo' },
  { code: 'PVT', nombre: 'Puerto Varas' },
  { code: 'WPU', nombre: 'Puerto Williams' },
  { code: 'PUN', nombre: 'Puno' },
  { code: 'PUQ', nombre: 'Punta Arenas' },
  { code: 'PDD', nombre: 'Punta del Diablo' },
  { code: 'PDP', nombre: 'Punta del Este' },
  { code: 'PLO', nombre: 'Punta Lobos' },
  { code: 'PUR', nombre: 'Purmamarca' },
  { code: 'PUT', nombre: 'Putre' },
  { code: 'PUY', nombre: 'Puyuhuapi' },
  { code: 'QND', nombre: 'Quindio' },
  { code: 'UIO', nombre: 'Quito' },
  { code: 'REC', nombre: 'Recife' },
  { code: 'RES', nombre: 'Resistencia' },
  { code: 'BAK', nombre: 'Rio Baker' },
  { code: 'RIO', nombre: 'Rio de Janeiro' },
  { code: 'RGL', nombre: 'Rio Gallegos' },
  { code: 'RGA', nombre: 'Rio Grande' },
  { code: 'ROY', nombre: 'Río Mayo' },
  { code: 'RGO', nombre: 'Rio Negro' },
  { code: 'RPU', nombre: 'Rio Puelo' },
  { code: 'ROS', nombre: 'Rosario' },
  { code: 'RBQ', nombre: 'Rurrenabaque' },
  { code: 'R40', nombre: 'Ruta Nacional 40' },
  { code: 'SAC', nombre: 'S. A. de los Cobres' },
  { code: 'LDX', nombre: 'Saint Laurent du Maroni' },
  { code: 'SGA', nombre: 'Salinas Grandes' },
  { code: 'SLA', nombre: 'Salta' },
  { code: 'SLO', nombre: 'Salto' },
  { code: 'SSA', nombre: 'Salvador Bahia' },
  { code: 'SAM', nombre: 'Samaipata' },
  { code: 'SDX', nombre: 'San Andres' },
  { code: 'SAI', nombre: 'San Antonio' },
  { code: 'SFO', nombre: 'San Francisco' },
  { code: 'UAQ', nombre: 'San Juan' },
  { code: 'SMA', nombre: 'San Martin de los Andes' },
  { code: 'SPA', nombre: 'San Pedro de Atacama' },
  { code: 'AFA', nombre: 'San Rafael' },
  { code: 'SSB', nombre: 'San Sebastian' },
  { code: 'STA', nombre: 'Santa Cruz' },
  { code: 'SRZ', nombre: 'Santa Cruz de la Sierra' },
  { code: 'SMR', nombre: 'Santa Marta' },
  { code: 'SCL', nombre: 'Santiago de Chile' },
  { code: 'SDE', nombre: 'Santiago del Estero' },
  { code: 'SSZ', nombre: 'Santos' },
  { code: 'SLM', nombre: 'Sao Luis do Maranhao' },
  { code: 'SAO', nombre: 'Sao Paulo' },
  { code: 'SAR', nombre: 'Sarmiento' },
  { code: 'SRE', nombre: 'Sucre' },
  { code: 'SUS', nombre: 'Susques' },
  { code: 'TDV', nombre: 'Tafi del Valle' },
  { code: 'TDY', nombre: 'Tandayapa' },
  { code: 'TAN', nombre: 'Tandil' },
  { code: 'TRJ', nombre: 'Tarija' },
  { code: 'ZCO', nombre: 'Temuco' },
  { code: 'TDF', nombre: 'Tierra del Fuego' },
  { code: 'TIL', nombre: 'Tilcara' },
  { code: 'TIM', nombre: 'Timaukel' },
  { code: 'TIR', nombre: 'Tiradentes' },
  { code: 'TGD', nombre: 'Tolar Grande' },
  { code: 'THL', nombre: 'Tolhuin' },
  { code: 'TDP', nombre: 'Torres del Paine' },
  { code: 'TRC', nombre: 'Trancoso' },
  { code: 'TYT', nombre: 'Treinta y Tres' },
  { code: 'REL', nombre: 'Trelew' },
  { code: 'TRV', nombre: 'Trevelin' },
  { code: 'TRU', nombre: 'Trujillo' },
  { code: 'TUC', nombre: 'Tucuman' },
  { code: 'UBT', nombre: 'Ubatuba' },
  { code: 'USH', nombre: 'Ushuaia' },
  { code: 'UYU', nombre: 'Uyuni' },
  { code: 'VDI', nombre: 'Valdivia' },
  { code: 'VPI', nombre: 'Valle de Pilolil' },
  { code: 'UCO', nombre: 'Valle de Uco' },
  { code: 'VAF', nombre: 'Valle Fertil' },
  { code: 'VLS', nombre: 'Valle Sagrado' },
  { code: 'VGR', nombre: 'Vallegrande' },
  { code: 'VAL', nombre: 'Valparaiso' },
  { code: 'VIC', nombre: 'Vicuña' },
  { code: 'VCC', nombre: 'Villa Cerro Castillo' },
  { code: 'VDL', nombre: 'Villa de Levya' },
  { code: 'VGB', nombre: 'Villa General Belgrano' },
  { code: 'VLA', nombre: 'Villa La Angostura' },
  { code: 'VMA', nombre: 'Villa Mar' },
  { code: 'VMQ', nombre: 'Villa Meliquina' },
  { code: 'VOH', nombre: 'Villa O´Higgins' },
  { code: 'VRT', nombre: 'Villa Rio Tranquilo' },
  { code: 'SAV', nombre: 'Villa San Agustin' },
  { code: 'VTR', nombre: 'Villa Traful' },
  { code: 'VLU', nombre: 'Villa Union' },
  { code: 'VIL', nombre: 'Villarrica' },
  { code: 'VLZ', nombre: 'Villazon' },
  { code: 'VNM', nombre: 'Viña del Mar' },
  { code: 'ZAP', nombre: 'Zapallar' },
]

export const nombreDestino = (code: string): string =>
  DESTINOS_TP.find(d => d.code === code)?.nombre ?? code
